name: check-codestyle
on:
  pull_request:

jobs:
  check-codestyle:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    name: check codestyle
    steps:
      - uses: actions/checkout@v2
      - name: Check core codestyle
        run: source ./codestyle.sh

